export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_PERSONNEL = "SET_PERSONNEL";
export const SET_SEARCH = "SET_SEARCH";
export const SET_PREVIOUS_PAGE_BUTTON = "SET_PREVIOUS_PAGE_BUTTON";
export const SET_NEXT_PAGE_BUTTON = "SET_NEXT_PAGE_BUTTON";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_PERSONNELS_PER_PAGE = "SET_PERSONNELS_PER_PAGE"
